// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    var animate, bars, start_index;
    bars = $('.code_stats span[data-lang][percent]');
    if (!bars.length) {
      return;
    }
    start_index = bars.length - 1;
    return (animate = function() {
      var bar;
      bar = $(bars[start_index--]);
      if (!bar.length) {
        return;
      }
      return bar.animate({
        width: bar.attr('percent')
      }, 600, animate);
    })();
  });

}).call(this);
